default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-movie-api_development

test:
  <<: *default
  database: rails-movie-api_test

production:
  <<: *default
  database: rails-movie-api_production
  username: rails-movie-api
  password: <%= ENV['RUNNING-BUDDY_DATABASE_PASSWORD'] %
